DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
  PERSON_ID  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(30)  NOT NULL,
  LAST_NAME  VARCHAR(30)  NOT NULL,
  SEX        INT(3)       NOT NULL,
  B_DATE     VARCHAR(10)  NULL,
  PHOTO      VARCHAR(40)  NOT NULL,
  NICKNAME   VARCHAR(40)  NULL,
  PRIMARY KEY (PERSON_ID) USING BTREE
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS LIKES;
CREATE TABLE LIKES (
  LIKES_ID  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PERSON_ID INT UNSIGNED NOT NULL,
  AMOUNT    LONG         NULL,
  PRIMARY KEY (LIKES_ID) USING BTREE,
  FOREIGN KEY (PERSON_ID)
  REFERENCES PERSON.PERSON (PERSON_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
