DROP TABLE IF EXISTS 'person';
CREATE TABLE person (
'USER_ID' INT UNSIGNED NOT NULL AUTO_INCREMENT,
'FIRST_NAME' VARCHAR(30) NOT NULL,
'LAST_NAME' VARCHAR(30) NOT NULL,
'SEX' INT(3) NOT NULL,
'BDATE' VARCHAR(10)  NULL,
'PHOTO' VARCHAR(40) NOT NULL,
'NICKNAME' VARCHAR(40)  NULL,
PRIMARY KEY ('USER_ID') USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS 'likes';
CREATE TABLE likes (
'LIKES_ID' INT UNSIGNED NOT NULL AUTO_INCREMENT,
'USER_ID' INT UNSIGNED NOT NULL,
'AMOUNT' LONG  NULL,
PRIMARY KEY ('LIKES_ID') USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;